version: "3.9"

services:
  invictus:
    image: invictus808/invictus:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: invictus
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - API_URL=http://localhost:3000/api
    ports:
      - "3000:3000"
    # volumes:
    #   - /path/to/src:/path/to/dst
    # depends_on:
    #   - serviceName