services:
  invictus:
    image: invictus808/invictus:1.0.0-SNAPSHOT
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: invictus
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL:-onboarding@resend.dev}
    ports:
      - "3000:3000"
    volumes:
      - ./src/:/app/src/
      - ./public/:/app/public/
      - ./content/:/app/content/
    # depends_on:
    #   - serviceName